#
#az aks command invoke \
#  --resource-group myResourceGroup \
#  --name myPrivateCluster \
#  --command "kubectl get pods -n kube-system"



trigger:
- none

pool:
  vmImage: `ubuntu-latest`

steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: az aks command invoke \
  --resource-group myResourceGroup \
  --name myPrivateCluster \
  --command "kubectl get pods -n kube-system"

  displayName: 'get private aks pods list'
