#
#az aks command invoke \
#  --resource-group myResourceGroup \
#  --name myPrivateCluster \
#  --command "kubectl get pods -n kube-system"



trigger:
  - none

variables:
  - group: Azure_Cred

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: az login --service-principal --username $(AZURE_CLIENT_ID)  --password $(AZURE_CLIENT_SECRET)   --tenant $(AZURE_TENANT_ID)
#- bash: az account get-access-token --subscription
  displayName: get access login

#- bash: az acr import -n aksdemoalpha --source mcr.microsoft.com/oss/nginx/nginx:1.21.4 --image aksdemoaplha/nginx:1.21.4
#  displayName: import to acr

- bash: az acr login -n aksdemoalpha 
  displayName: login ACR

- bash: az acr repository list --name aksdemoalpha --output table
  displayName: show artifacts

#- bash: az acr repository show-tags --name aksdemoalpha --repository nginx

- bash: az aks get-credentials --resource-group aks-project --name aks-dinesh --overwrite-existing
  displayName: login to aks

- bash: az aks command invoke --resource-group aks-project --name aks-dinesh --command "kubectl get nodes"
  displayName: 'get private aks pods list'

#steps:
#- checkout: self

#- task: AzureCLI@2
#  displayName: Azure CLI
#  inputs:
#    azureSubscription: 57498e65-d4a7-4935-b48b-a46c85d91999
#    scriptType: ps
#    scriptLocation: inlineScript
#    inlineScript: |
#      az --version
#      az aks command invoke --resource-group aks-project  --name aks-dinesh --command "kubectl get pods -n kube-system"